// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: socks5_protocal.proto

package com.github.xsocks.proto;

public final class Socks5 {
  private Socks5() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code Socks5.AuthMethod}
   */
  public enum AuthMethod
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_AUTH = 1;</code>
     */
    NO_AUTH(0, 1),
    /**
     * <code>GSSAPI = 2;</code>
     */
    GSSAPI(1, 2),
    /**
     * <code>PASSWORD = 3;</code>
     */
    PASSWORD(2, 3),
    ;

    /**
     * <code>NO_AUTH = 1;</code>
     */
    public static final int NO_AUTH_VALUE = 1;
    /**
     * <code>GSSAPI = 2;</code>
     */
    public static final int GSSAPI_VALUE = 2;
    /**
     * <code>PASSWORD = 3;</code>
     */
    public static final int PASSWORD_VALUE = 3;


    public final int getNumber() { return value; }

    public static AuthMethod valueOf(int value) {
      switch (value) {
        case 1: return NO_AUTH;
        case 2: return GSSAPI;
        case 3: return PASSWORD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthMethod>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<AuthMethod>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthMethod>() {
            public AuthMethod findValueByNumber(int number) {
              return AuthMethod.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.xsocks.proto.Socks5.getDescriptor().getEnumTypes().get(0);
    }

    private static final AuthMethod[] VALUES = values();

    public static AuthMethod valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private AuthMethod(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Socks5.AuthMethod)
  }

  public interface AuthRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Socks5.AuthRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>repeated .Socks5.AuthMethod methods = 2;</code>
     */
    java.util.List<com.github.xsocks.proto.Socks5.AuthMethod> getMethodsList();
    /**
     * <code>repeated .Socks5.AuthMethod methods = 2;</code>
     */
    int getMethodsCount();
    /**
     * <code>repeated .Socks5.AuthMethod methods = 2;</code>
     */
    com.github.xsocks.proto.Socks5.AuthMethod getMethods(int index);
  }
  /**
   * Protobuf type {@code Socks5.AuthRequest}
   */
  public static final class AuthRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Socks5.AuthRequest)
      AuthRequestOrBuilder {
    // Use AuthRequest.newBuilder() to construct.
    private AuthRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthRequest defaultInstance;
    public static AuthRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AuthRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.github.xsocks.proto.Socks5.AuthMethod value = com.github.xsocks.proto.Socks5.AuthMethod.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
                } else {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  methods_ = new java.util.ArrayList<com.github.xsocks.proto.Socks5.AuthMethod>();
                  mutable_bitField0_ |= 0x00000002;
                }
                methods_.add(value);
              }
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                com.github.xsocks.proto.Socks5.AuthMethod value = com.github.xsocks.proto.Socks5.AuthMethod.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                  } else {
                  if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    methods_ = new java.util.ArrayList<com.github.xsocks.proto.Socks5.AuthMethod>();
                    mutable_bitField0_ |= 0x00000002;
                  }
                  methods_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          methods_ = java.util.Collections.unmodifiableList(methods_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xsocks.proto.Socks5.AuthRequest.class, com.github.xsocks.proto.Socks5.AuthRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthRequest> PARSER =
        new com.google.protobuf.AbstractParser<AuthRequest>() {
      public AuthRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int METHODS_FIELD_NUMBER = 2;
    private java.util.List<com.github.xsocks.proto.Socks5.AuthMethod> methods_;
    /**
     * <code>repeated .Socks5.AuthMethod methods = 2;</code>
     */
    public java.util.List<com.github.xsocks.proto.Socks5.AuthMethod> getMethodsList() {
      return methods_;
    }
    /**
     * <code>repeated .Socks5.AuthMethod methods = 2;</code>
     */
    public int getMethodsCount() {
      return methods_.size();
    }
    /**
     * <code>repeated .Socks5.AuthMethod methods = 2;</code>
     */
    public com.github.xsocks.proto.Socks5.AuthMethod getMethods(int index) {
      return methods_.get(index);
    }

    private void initFields() {
      version_ = 0;
      methods_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      for (int i = 0; i < methods_.size(); i++) {
        output.writeEnum(2, methods_.get(i).getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < methods_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(methods_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * methods_.size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.AuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.xsocks.proto.Socks5.AuthRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Socks5.AuthRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Socks5.AuthRequest)
        com.github.xsocks.proto.Socks5.AuthRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xsocks.proto.Socks5.AuthRequest.class, com.github.xsocks.proto.Socks5.AuthRequest.Builder.class);
      }

      // Construct using com.github.xsocks.proto.Socks5.AuthRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthRequest_descriptor;
      }

      public com.github.xsocks.proto.Socks5.AuthRequest getDefaultInstanceForType() {
        return com.github.xsocks.proto.Socks5.AuthRequest.getDefaultInstance();
      }

      public com.github.xsocks.proto.Socks5.AuthRequest build() {
        com.github.xsocks.proto.Socks5.AuthRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.xsocks.proto.Socks5.AuthRequest buildPartial() {
        com.github.xsocks.proto.Socks5.AuthRequest result = new com.github.xsocks.proto.Socks5.AuthRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          methods_ = java.util.Collections.unmodifiableList(methods_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.methods_ = methods_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.xsocks.proto.Socks5.AuthRequest) {
          return mergeFrom((com.github.xsocks.proto.Socks5.AuthRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.xsocks.proto.Socks5.AuthRequest other) {
        if (other == com.github.xsocks.proto.Socks5.AuthRequest.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (!other.methods_.isEmpty()) {
          if (methods_.isEmpty()) {
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMethodsIsMutable();
            methods_.addAll(other.methods_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.xsocks.proto.Socks5.AuthRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.xsocks.proto.Socks5.AuthRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.github.xsocks.proto.Socks5.AuthMethod> methods_ =
        java.util.Collections.emptyList();
      private void ensureMethodsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          methods_ = new java.util.ArrayList<com.github.xsocks.proto.Socks5.AuthMethod>(methods_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated .Socks5.AuthMethod methods = 2;</code>
       */
      public java.util.List<com.github.xsocks.proto.Socks5.AuthMethod> getMethodsList() {
        return java.util.Collections.unmodifiableList(methods_);
      }
      /**
       * <code>repeated .Socks5.AuthMethod methods = 2;</code>
       */
      public int getMethodsCount() {
        return methods_.size();
      }
      /**
       * <code>repeated .Socks5.AuthMethod methods = 2;</code>
       */
      public com.github.xsocks.proto.Socks5.AuthMethod getMethods(int index) {
        return methods_.get(index);
      }
      /**
       * <code>repeated .Socks5.AuthMethod methods = 2;</code>
       */
      public Builder setMethods(
          int index, com.github.xsocks.proto.Socks5.AuthMethod value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .Socks5.AuthMethod methods = 2;</code>
       */
      public Builder addMethods(com.github.xsocks.proto.Socks5.AuthMethod value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .Socks5.AuthMethod methods = 2;</code>
       */
      public Builder addAllMethods(
          java.lang.Iterable<? extends com.github.xsocks.proto.Socks5.AuthMethod> values) {
        ensureMethodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methods_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .Socks5.AuthMethod methods = 2;</code>
       */
      public Builder clearMethods() {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Socks5.AuthRequest)
    }

    static {
      defaultInstance = new AuthRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Socks5.AuthRequest)
  }

  public interface AuthResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Socks5.AuthResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required .Socks5.AuthMethod method = 2;</code>
     */
    boolean hasMethod();
    /**
     * <code>required .Socks5.AuthMethod method = 2;</code>
     */
    com.github.xsocks.proto.Socks5.AuthMethod getMethod();
  }
  /**
   * Protobuf type {@code Socks5.AuthResponse}
   */
  public static final class AuthResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Socks5.AuthResponse)
      AuthResponseOrBuilder {
    // Use AuthResponse.newBuilder() to construct.
    private AuthResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthResponse defaultInstance;
    public static AuthResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AuthResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.github.xsocks.proto.Socks5.AuthMethod value = com.github.xsocks.proto.Socks5.AuthMethod.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                method_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xsocks.proto.Socks5.AuthResponse.class, com.github.xsocks.proto.Socks5.AuthResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthResponse> PARSER =
        new com.google.protobuf.AbstractParser<AuthResponse>() {
      public AuthResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private com.github.xsocks.proto.Socks5.AuthMethod method_;
    /**
     * <code>required .Socks5.AuthMethod method = 2;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Socks5.AuthMethod method = 2;</code>
     */
    public com.github.xsocks.proto.Socks5.AuthMethod getMethod() {
      return method_;
    }

    private void initFields() {
      version_ = 0;
      method_ = com.github.xsocks.proto.Socks5.AuthMethod.NO_AUTH;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, method_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, method_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.AuthResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.xsocks.proto.Socks5.AuthResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Socks5.AuthResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Socks5.AuthResponse)
        com.github.xsocks.proto.Socks5.AuthResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xsocks.proto.Socks5.AuthResponse.class, com.github.xsocks.proto.Socks5.AuthResponse.Builder.class);
      }

      // Construct using com.github.xsocks.proto.Socks5.AuthResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = com.github.xsocks.proto.Socks5.AuthMethod.NO_AUTH;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_AuthResponse_descriptor;
      }

      public com.github.xsocks.proto.Socks5.AuthResponse getDefaultInstanceForType() {
        return com.github.xsocks.proto.Socks5.AuthResponse.getDefaultInstance();
      }

      public com.github.xsocks.proto.Socks5.AuthResponse build() {
        com.github.xsocks.proto.Socks5.AuthResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.xsocks.proto.Socks5.AuthResponse buildPartial() {
        com.github.xsocks.proto.Socks5.AuthResponse result = new com.github.xsocks.proto.Socks5.AuthResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.method_ = method_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.xsocks.proto.Socks5.AuthResponse) {
          return mergeFrom((com.github.xsocks.proto.Socks5.AuthResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.xsocks.proto.Socks5.AuthResponse other) {
        if (other == com.github.xsocks.proto.Socks5.AuthResponse.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasMethod()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.xsocks.proto.Socks5.AuthResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.xsocks.proto.Socks5.AuthResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private com.github.xsocks.proto.Socks5.AuthMethod method_ = com.github.xsocks.proto.Socks5.AuthMethod.NO_AUTH;
      /**
       * <code>required .Socks5.AuthMethod method = 2;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Socks5.AuthMethod method = 2;</code>
       */
      public com.github.xsocks.proto.Socks5.AuthMethod getMethod() {
        return method_;
      }
      /**
       * <code>required .Socks5.AuthMethod method = 2;</code>
       */
      public Builder setMethod(com.github.xsocks.proto.Socks5.AuthMethod value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Socks5.AuthMethod method = 2;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        method_ = com.github.xsocks.proto.Socks5.AuthMethod.NO_AUTH;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Socks5.AuthResponse)
    }

    static {
      defaultInstance = new AuthResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Socks5.AuthResponse)
  }

  public interface ConnectionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Socks5.ConnectionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required uint32 command = 2;</code>
     */
    boolean hasCommand();
    /**
     * <code>required uint32 command = 2;</code>
     */
    int getCommand();

    /**
     * <code>required uint32 address_type = 3;</code>
     */
    boolean hasAddressType();
    /**
     * <code>required uint32 address_type = 3;</code>
     */
    int getAddressType();

    /**
     * <code>required bytes address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>required bytes address = 4;</code>
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>required bytes port = 5;</code>
     */
    boolean hasPort();
    /**
     * <code>required bytes port = 5;</code>
     */
    com.google.protobuf.ByteString getPort();
  }
  /**
   * Protobuf type {@code Socks5.ConnectionRequest}
   */
  public static final class ConnectionRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Socks5.ConnectionRequest)
      ConnectionRequestOrBuilder {
    // Use ConnectionRequest.newBuilder() to construct.
    private ConnectionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConnectionRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConnectionRequest defaultInstance;
    public static ConnectionRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ConnectionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConnectionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              command_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              addressType_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              address_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              port_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xsocks.proto.Socks5.ConnectionRequest.class, com.github.xsocks.proto.Socks5.ConnectionRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ConnectionRequest> PARSER =
        new com.google.protobuf.AbstractParser<ConnectionRequest>() {
      public ConnectionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConnectionRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectionRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int COMMAND_FIELD_NUMBER = 2;
    private int command_;
    /**
     * <code>required uint32 command = 2;</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 command = 2;</code>
     */
    public int getCommand() {
      return command_;
    }

    public static final int ADDRESS_TYPE_FIELD_NUMBER = 3;
    private int addressType_;
    /**
     * <code>required uint32 address_type = 3;</code>
     */
    public boolean hasAddressType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 address_type = 3;</code>
     */
    public int getAddressType() {
      return addressType_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>required bytes address = 4;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes address = 4;</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString port_;
    /**
     * <code>required bytes port = 5;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes port = 5;</code>
     */
    public com.google.protobuf.ByteString getPort() {
      return port_;
    }

    private void initFields() {
      version_ = 0;
      command_ = 0;
      addressType_ = 0;
      address_ = com.google.protobuf.ByteString.EMPTY;
      port_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddressType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, command_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, addressType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, address_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, port_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, command_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, addressType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, address_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.xsocks.proto.Socks5.ConnectionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Socks5.ConnectionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Socks5.ConnectionRequest)
        com.github.xsocks.proto.Socks5.ConnectionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xsocks.proto.Socks5.ConnectionRequest.class, com.github.xsocks.proto.Socks5.ConnectionRequest.Builder.class);
      }

      // Construct using com.github.xsocks.proto.Socks5.ConnectionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        addressType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionRequest_descriptor;
      }

      public com.github.xsocks.proto.Socks5.ConnectionRequest getDefaultInstanceForType() {
        return com.github.xsocks.proto.Socks5.ConnectionRequest.getDefaultInstance();
      }

      public com.github.xsocks.proto.Socks5.ConnectionRequest build() {
        com.github.xsocks.proto.Socks5.ConnectionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.xsocks.proto.Socks5.ConnectionRequest buildPartial() {
        com.github.xsocks.proto.Socks5.ConnectionRequest result = new com.github.xsocks.proto.Socks5.ConnectionRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.addressType_ = addressType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.xsocks.proto.Socks5.ConnectionRequest) {
          return mergeFrom((com.github.xsocks.proto.Socks5.ConnectionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.xsocks.proto.Socks5.ConnectionRequest other) {
        if (other == com.github.xsocks.proto.Socks5.ConnectionRequest.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasAddressType()) {
          setAddressType(other.getAddressType());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        if (!hasAddressType()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.xsocks.proto.Socks5.ConnectionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.xsocks.proto.Socks5.ConnectionRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private int command_ ;
      /**
       * <code>required uint32 command = 2;</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 command = 2;</code>
       */
      public int getCommand() {
        return command_;
      }
      /**
       * <code>required uint32 command = 2;</code>
       */
      public Builder setCommand(int value) {
        bitField0_ |= 0x00000002;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 command = 2;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = 0;
        onChanged();
        return this;
      }

      private int addressType_ ;
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public boolean hasAddressType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public int getAddressType() {
        return addressType_;
      }
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public Builder setAddressType(int value) {
        bitField0_ |= 0x00000004;
        addressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public Builder clearAddressType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        addressType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes address = 4;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes address = 4;</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>required bytes address = 4;</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes address = 4;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString port_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes port = 5;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes port = 5;</code>
       */
      public com.google.protobuf.ByteString getPort() {
        return port_;
      }
      /**
       * <code>required bytes port = 5;</code>
       */
      public Builder setPort(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes port = 5;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Socks5.ConnectionRequest)
    }

    static {
      defaultInstance = new ConnectionRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Socks5.ConnectionRequest)
  }

  public interface ConnectionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Socks5.ConnectionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>required uint32 status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>required uint32 status = 2;</code>
     */
    int getStatus();

    /**
     * <code>required uint32 address_type = 3;</code>
     */
    boolean hasAddressType();
    /**
     * <code>required uint32 address_type = 3;</code>
     */
    int getAddressType();

    /**
     * <code>required bytes address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>required bytes address = 4;</code>
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>required bytes port = 5;</code>
     */
    boolean hasPort();
    /**
     * <code>required bytes port = 5;</code>
     */
    com.google.protobuf.ByteString getPort();
  }
  /**
   * Protobuf type {@code Socks5.ConnectionResponse}
   */
  public static final class ConnectionResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Socks5.ConnectionResponse)
      ConnectionResponseOrBuilder {
    // Use ConnectionResponse.newBuilder() to construct.
    private ConnectionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ConnectionResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ConnectionResponse defaultInstance;
    public static ConnectionResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ConnectionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ConnectionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              addressType_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              address_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              port_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xsocks.proto.Socks5.ConnectionResponse.class, com.github.xsocks.proto.Socks5.ConnectionResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ConnectionResponse> PARSER =
        new com.google.protobuf.AbstractParser<ConnectionResponse>() {
      public ConnectionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConnectionResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ConnectionResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>required uint32 status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int ADDRESS_TYPE_FIELD_NUMBER = 3;
    private int addressType_;
    /**
     * <code>required uint32 address_type = 3;</code>
     */
    public boolean hasAddressType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 address_type = 3;</code>
     */
    public int getAddressType() {
      return addressType_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>required bytes address = 4;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes address = 4;</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString port_;
    /**
     * <code>required bytes port = 5;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes port = 5;</code>
     */
    public com.google.protobuf.ByteString getPort() {
      return port_;
    }

    private void initFields() {
      version_ = 0;
      status_ = 0;
      addressType_ = 0;
      address_ = com.google.protobuf.ByteString.EMPTY;
      port_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddressType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, addressType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, address_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, port_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, addressType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, address_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.xsocks.proto.Socks5.ConnectionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.github.xsocks.proto.Socks5.ConnectionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Socks5.ConnectionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Socks5.ConnectionResponse)
        com.github.xsocks.proto.Socks5.ConnectionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xsocks.proto.Socks5.ConnectionResponse.class, com.github.xsocks.proto.Socks5.ConnectionResponse.Builder.class);
      }

      // Construct using com.github.xsocks.proto.Socks5.ConnectionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        addressType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.xsocks.proto.Socks5.internal_static_Socks5_ConnectionResponse_descriptor;
      }

      public com.github.xsocks.proto.Socks5.ConnectionResponse getDefaultInstanceForType() {
        return com.github.xsocks.proto.Socks5.ConnectionResponse.getDefaultInstance();
      }

      public com.github.xsocks.proto.Socks5.ConnectionResponse build() {
        com.github.xsocks.proto.Socks5.ConnectionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.xsocks.proto.Socks5.ConnectionResponse buildPartial() {
        com.github.xsocks.proto.Socks5.ConnectionResponse result = new com.github.xsocks.proto.Socks5.ConnectionResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.addressType_ = addressType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.xsocks.proto.Socks5.ConnectionResponse) {
          return mergeFrom((com.github.xsocks.proto.Socks5.ConnectionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.xsocks.proto.Socks5.ConnectionResponse other) {
        if (other == com.github.xsocks.proto.Socks5.ConnectionResponse.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasAddressType()) {
          setAddressType(other.getAddressType());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasAddressType()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.xsocks.proto.Socks5.ConnectionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.xsocks.proto.Socks5.ConnectionResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>required uint32 status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required uint32 status = 2;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 status = 2;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      private int addressType_ ;
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public boolean hasAddressType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public int getAddressType() {
        return addressType_;
      }
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public Builder setAddressType(int value) {
        bitField0_ |= 0x00000004;
        addressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 address_type = 3;</code>
       */
      public Builder clearAddressType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        addressType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes address = 4;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes address = 4;</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>required bytes address = 4;</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes address = 4;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString port_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes port = 5;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes port = 5;</code>
       */
      public com.google.protobuf.ByteString getPort() {
        return port_;
      }
      /**
       * <code>required bytes port = 5;</code>
       */
      public Builder setPort(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes port = 5;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Socks5.ConnectionResponse)
    }

    static {
      defaultInstance = new ConnectionResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Socks5.ConnectionResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Socks5_AuthRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Socks5_AuthRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Socks5_AuthResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Socks5_AuthResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Socks5_ConnectionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Socks5_ConnectionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Socks5_ConnectionResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Socks5_ConnectionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025socks5_protocal.proto\022\006Socks5\"C\n\013AuthR" +
      "equest\022\017\n\007version\030\001 \002(\r\022#\n\007methods\030\002 \003(\016" +
      "2\022.Socks5.AuthMethod\"C\n\014AuthResponse\022\017\n\007" +
      "version\030\001 \002(\r\022\"\n\006method\030\002 \002(\0162\022.Socks5.A" +
      "uthMethod\"j\n\021ConnectionRequest\022\017\n\007versio" +
      "n\030\001 \002(\r\022\017\n\007command\030\002 \002(\r\022\024\n\014address_type" +
      "\030\003 \002(\r\022\017\n\007address\030\004 \002(\014\022\014\n\004port\030\005 \002(\014\"j\n" +
      "\022ConnectionResponse\022\017\n\007version\030\001 \002(\r\022\016\n\006" +
      "status\030\002 \002(\r\022\024\n\014address_type\030\003 \002(\r\022\017\n\007ad" +
      "dress\030\004 \002(\014\022\014\n\004port\030\005 \002(\014*3\n\nAuthMethod\022",
      "\013\n\007NO_AUTH\020\001\022\n\n\006GSSAPI\020\002\022\014\n\010PASSWORD\020\003B!" +
      "\n\027com.github.xsocks.protoB\006Socks5"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Socks5_AuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Socks5_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Socks5_AuthRequest_descriptor,
        new java.lang.String[] { "Version", "Methods", });
    internal_static_Socks5_AuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Socks5_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Socks5_AuthResponse_descriptor,
        new java.lang.String[] { "Version", "Method", });
    internal_static_Socks5_ConnectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Socks5_ConnectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Socks5_ConnectionRequest_descriptor,
        new java.lang.String[] { "Version", "Command", "AddressType", "Address", "Port", });
    internal_static_Socks5_ConnectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Socks5_ConnectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Socks5_ConnectionResponse_descriptor,
        new java.lang.String[] { "Version", "Status", "AddressType", "Address", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
